fix padding check, default ignore_newline
kxcteam/kxclib-ocaml pull request #33
Opened 2023-03-02 10:41 UTC by kxc-ryfujis

- should fix #25 
- should fix #26

2023-03-02 10:43 UTC, kxc-ryfujis commented on kxclib.ml
>          else offset, end_index, len
for reviewers:
ignore した後の長さが 4 の倍数 で検査するように変更

2023-03-02 10:48 UTC, kxc-ryfujis commented on kxclib.ml
> +                else invalid_arg' "Base64.decode: invalid pad len '%d'" pad_count
for reviewers:
pad が現れてから、それ以降が ignore を除き 1 または 2 個 (自身を含む) の pad であるかで検査するように変更。

2023-03-02 17:33 UTC, haochenx requested changes

2023-03-02 17:33 UTC, haochenx commented on kxclib.ml
> +    let ignore_newline = true
RFC4648 的には newline を ignore してはいけない
https://www.rfc-editor.org/rfc/rfc4648#section-3.3

2023-03-02 17:33 UTC, haochenx commented on kxclib.ml
> +    let ignore_newline = true
RFC4648 と同じく ignore してはいけない

2023-03-02 17:33 UTC, haochenx commented on kxclib.ml
>    include Make(Config_rfc4648)
```
module Config_rfc4648_relaxed = struct
  include Config_rfc4648
  let ignore_newline = true
end
```
を用意して、代りにこちらを `include Make(Config_rfc4648_relaxed)` しましょう

2023-03-02 17:34 UTC, haochenx commented on kxclib.ml
>    include Make(Config_rfc4648)
あ、これは https://github.com/kxcteam/kxclib-ocaml/issues/26 の scope か。
すみません、この PR においては無視しましょう

2023-03-02 18:08 UTC, haochenx commented on kxclib.ml
> +                let pad_counter acc ci =
以下 post-merge でもよいため、 non-blocking ですが、
1. config に `val validate_padding : bool` も追加したい
2. padding error になった場合 catch しやすいように `exception Invalid_base64_padding of [ `message of string ] option` という exception を `module Base64` の scope で宣言してそちらを使ってほしい
    - exception を宣言したら下記のように pretty printer も register してほしい
      ```ocaml
      let () =
        Printexc.register_printer (function
            | Invalid_base64_padding None ->
               Some "Invalid_base64_padding"
            | Invalid_base64_padding (Some (`message msg)) ->
               Some (sprintf "Invalid_base64_padding(%s)" msg)
            | _ -> None)
          ```

2023-03-03 05:20 UTC, kxc-ryfujis commented on kxclib.ml
>    include Make(Config_rfc4648)
newline についてはこの PR でやってしまいますね。

2023-03-03 05:22 UTC, kxc-ryfujis commented on kxclib.ml
> +      let counter acc i =
fixed at https://github.com/kxcteam/kxclib-ocaml/pull/33/commits/28a4d1a6da1354b73277398033016b57f03b3a21

2023-03-03 05:22 UTC, kxc-ryfujis commented on kxclib.ml
> +    let len_without_ignore ?(offset=0) ?len (input: Bytes.t): int =
fixed at https://github.com/kxcteam/kxclib-ocaml/pull/33/commits/28a4d1a6da1354b73277398033016b57f03b3a21

2023-03-03 05:22 UTC, kxc-ryfujis commented on kxclib.ml
> +    let ignore_newline = true
fixed at https://github.com/kxcteam/kxclib-ocaml/pull/33/commits/725dfe229194ef53d9c48d5cdda460535f04d756

2023-03-03 05:22 UTC, kxc-ryfujis commented on kxclib.ml
> +    let ignore_newline = true
fixed at https://github.com/kxcteam/kxclib-ocaml/pull/33/commits/725dfe229194ef53d9c48d5cdda460535f04d756

2023-03-03 05:23 UTC, kxc-ryfujis commented on kxclib.ml
>    include Make(Config_rfc4648)
fixed at https://github.com/kxcteam/kxclib-ocaml/pull/33/commits/725dfe229194ef53d9c48d5cdda460535f04d756

2023-03-03 05:25 UTC, kxc-ryfujis commented on kxclib.ml
> +                let pad_counter acc ci =
2. padding error になった場合 catch しやすいように 
```
 exception Invalid_base64_padding of [ `message of string ] option
```
という exception を `module Base64` の scope で宣言してそちらを使ってほしい

2023-03-03 06:16 UTC, kxc-ryfujis commented on kxclib.ml
> +      let counter acc i =
fixed at https://github.com/kxcteam/kxclib-ocaml/pull/33/commits/a2a80244b7607c642e1434ec8ed4bd3858761755

2023-03-03 07:33 UTC, kxc-ryfujis commented on kxclib.ml
> +                let pad_counter acc ci =
fixed at https://github.com/kxcteam/kxclib-ocaml/pull/33/commits/5b26fede0f6821c0df5d6a1e05658f3cc8880002

2023-03-03 09:12 UTC, haochenx requested changes

2023-03-03 09:12 UTC, haochenx commented on kxclib.ml
> +  exception Invalid_base64_padding_char of [`char of char] * [`index of int]
Invalid_base64_padding_char と Invalid_base64_padding_len を merge しましょう

2023-03-03 18:58 UTC, haochenx approved these changes

2023-03-03 19:06 UTC, merged